name: Build and Release Binary

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"

      - name: Run tests
        run: |
          make test

      - name: Build binary
        run: |
          make build

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: sps
          path: build/sps

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: sps
          path: ./dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/sps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
